# Generated by Django 4.1.4 on 2024-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=200)),
                ('starttime', models.CharField(default='NONTOUCH', max_length=50)),
                ('trycount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('disable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ApiStatus',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
