# Generated by Django 4.2.4 on 2023-08-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='model',
            new_name='model_form',
        ),
    ]
