# Generated by Django 4.2.4 on 2023-08-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_model_section_model_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='model_form',
            new_name='model',
        ),
        migrations.AddField(
            model_name='models',
            name='default',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
