# Generated by Django 4.2.4 on 2023-08-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_model_form_section_model_models_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name_plural': 'Models'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='model',
            new_name='model_root',
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
