# Generated by Django 4.2.4 on 2023-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_models_options_rename_model_section_model_root_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='model_root',
        ),
        migrations.AddField(
            model_name='section',
            name='model_config',
            field=models.ManyToManyField(to='backend_api.models'),
        ),
    ]
