# Generated by Django 4.2.4 on 2023-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_remove_section_model_root_section_model_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='model_config',
        ),
        migrations.AddField(
            model_name='section',
            name='model_config',
            field=models.CharField(choices=[('text', 'text'), ('text', 'text')], default='text', max_length=100),
        ),
    ]
