# Generated by Django 4.2.4 on 2023-08-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_section_model_config_section_model_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='model_config',
        ),
        migrations.AddField(
            model_name='models',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.section'),
        ),
    ]
