# Generated by Django 4.2.4 on 2023-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_remove_section_model_config_models_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='model_config',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
