# Generated by Django 4.2.4 on 2023-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_remove_models_section_section_model_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
