# Generated by Django 4.2.4 on 2023-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_models_id_alter_section_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.RemoveField(
            model_name='section',
            name='model_config',
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
