# Generated by Django 4.2.4 on 2023-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_delete_models_remove_section_model_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FilePathField()),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
