# Generated by Django 4.2.4 on 2023-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_filenames_alter_section_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filenames',
            options={'verbose_name_plural': 'Filenames'},
        ),
        migrations.AlterField(
            model_name='filenames',
            name='name',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
