# Generated by Django 4.2.4 on 2023-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_apistatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apistatus',
            options={'verbose_name_plural': 'ApiStatus'},
        ),
        migrations.AlterField(
            model_name='apistatus',
            name='api',
            field=models.CharField(max_length=200),
        ),
    ]
