myaddress = 'ShirSpamer@outlook.com'
smtppswd = '#Aren2021'
smtpservername = 'smtp-mail.outlook.com'
port = 587

class10 = [
    
    # physics math 46
    'avagyanelen@shirakatsy.am',
    'avetyangarnik@shirakatsy.am', 
    'badalyandavit@shirakatsy.am', 
    'bostanjyananahit@shirakatsy.am', 
    'gasparyannorayr@shirakatsy.am', 
    'grigoryanarman2@shirakatsy.am', 
    'grigoryanlusi@shirakatsy.am', 
    'hakobyanemil@shirakatsy.am', 
    'hakobyanmanya@shirakatsy.am', 
    'hakobyanmiqayel@shirakatsy.am', 
    'harutyunyanelen@shirakatsy.am', 
    'hovhannisyanmari1@shirakatsy.am', 
    'lalazaryankarine@shirakatsy.am', 
    'madoyanhayk@shirakatsy.am', 
    'manukyanarpi@shirakatsy.am', 
    'manukyandavit@shirakatsy.am', 
    'mejlumyanartashes@shirakatsy.am', 
    'safaryangagik@shirakatsy.am', 
    'sargsyanvaleri@shirakatsy.am', 
    'tatyanrouben@shirakatsy.am', 
    'tuhkaryannarekvan@shirakatsy.am',

    # physics math 47
    'aghajanyanarsen@shirakatsy.am',
    'babayanyuri@shirakatsy.am',
    'badalyanastghik@shirakatsy.am',
    'danielyanani@shirakatsy.am',
    'gevorgyanemil@shirakatsy.am',
    'harutyunyandavit1@shirakatsy.am', 
    'karapetyaneduard@shirakatsy.am', 
    'khanoyanerik@shirakatsy.am', 
    'makyanmark@shirakatsy.am', 
    'manucharyannazeli@shirakatsy.am', 
    'marabyangevorg@shirakatsy.am', 
    'mazejyanmark@shirakatsy.am', 
    'mirzoyanariana@shirakatsy.am', 
    'muradyanvigen@shirakatsy.am', 
    'sargsyanani1@shirakatsy.am', 
    'sargsyananush@shirakatsy.am', 
    'sargsyanaren@shirakatsy.am', 
    'sargsyanarsen@shirakatsy.am',
    'stepanyanmane@shirakatsy.am',
    'vanyandavit@shirakatsy.am',
    'zargaryantatev@shirakatsy.am',
    
    # social science 45
    'aghabalyannarek@shirakatsy.am', 
    'asrievaelen@shirakatsy.am', 
    'baghdasaryanviktoria@shirakatsy.am', 
    'gevorgyanelina@shirakatsy.am', 
    'ghambaryanhrach@shirakatsy.am', 
    'hakobyanhakob@shirakatsy.am', 
    'hovhannisyanhovhannes@shirakatsy.am', 
    'ispiryanemma@shirakatsy.am', 
    'karapetyaniren@shirakatsy.am',
    'khandanyanaraz@shirakatsy.am', 
    'manukyantaguhi@shirakatsy.am', 
    'ohanyanelen@shirakatsy.am', 
    'sahakyanartavazd@shirakatsy.am', 
    'santrosyanmarina@shirakatsy.am', 
    'sardaryannatali@shirakatsy.am', 
    'sargsyanruzanna@shirakatsy.am', 
    'suqiasyanmila@shirakatsy.am', 
    'tumasyanmariam@shirakatsy.am', 
    'tunyannarek@shirakatsy.am',

    # economics 41
    'adilkhanyanyeva@shirakatsy.am', 
    'alikhanyanrobert@shirakatsy.am', 
    'arajyanastghik@shirakatsy.am', 
    'arstamyanvram@shirakatsy.am', 
    'babakhanyangayane@shirakatsy.am', 
    'baghryanelmira@shirakatsy.am', 
    'davtyanhovhannes@shirakatsy.am', 
    'gevorgyannarine@shirakatsy.am', 
    'ghahramanyanhayk@shirakatsy.am', 
    'gharsayannarek@shirakatsy.am', 
    'gyurjyanviktoria@shirakatsy.am', 
    'haroyanani@shirakatsy.am', 
    'harutyunyanmarina@shirakatsy.am', 
    'mirzoyanmarianna@shirakatsy.am', 
    'safaryanelen@shirakatsy.am', 
    'saghatelyanani1@shirakatsy.am', 
    'sahakyanvache@shirakatsy.am', 
    'suqiasyansyuzi@shirakatsy.am', 
    'vardanyansofi@shirakatsy.am',

    # economics 42
    'abrahamyansergey@shirakatsy.am', 
    'adamyangarri@shirakatsy.am', 
    'alikhanyanhayk@shirakatsy.am', 
    'buniatyandavit@shirakatsy.am', 
    'davoyanqristine@shirakatsy.am', 
    'eganyanelen@shirakatsy.am', 
    'galstyanlevon@shirakatsy.am', 
    'gasparyanmikhael@shirakatsy.am', 
    'harutyunyanlia@shirakatsy.am', 
    'igityanhamlet@shirakatsy.am', 
    'khachatryankarine@shirakatsy.am', 
    'khalatyanmariam@shirakatsy.am', 
    'petrosyanrobert@shirakatsy.am', 
    'qasabyanelina@shirakatsy.am', 
    'shamshyanevelina@shirakatsy.am', 
    'shamshyansofi@shirakatsy.am', 
    'stepanyangayane@shirakatsy.am', 
    'taroyanameli@shirakatsy.am', 
    'vardanyanvane@shirakatsy.am', 
    'voskanyanmariam1@shirakatsy.am',

    # economics 43
    'baghdasaryannarek@shirakatsy.am', 
    'davtyanagapi@shirakatsy.am', 
    'grigoryanvigen@shirakatsy.am', 
    'harutyunyangayane@shirakatsy.am', 
    'harutyunyanmher@shirakatsy.am', 
    'harutyunyanvahagn@shirakatsy.am', 
    'hayrumyanzaruhi@shirakatsy.am', 
    'khachatryaneva@shirakatsy.am', 
    'khachatryanhovhannes@shirakatsy.am', 
    'mikayelyannarek@shirakatsy.am', 
    'minasyanyana@shirakatsy.am', 
    'samsonyangor@shirakatsy.am', 
    'shamirzayanvahe@shirakatsy.am', 
    'sinanyanmher@shirakatsy.am', 
    'tadevosyanshoghine@shirakatsy.am', 
    'tumasyanani@shirakatsy.am', 
    'vardanyanlevon@shirakatsy.am', 
    'varderesyanavetis@shirakatsy.am', 
    'yeghoyantigran@shirakatsy.am',

    # science 44
    'apresyanmilena@shirakatsy.am', 
    'charkhchyaninesa@shirakatsy.am', 
    'gasparyannare@shirakatsy.am', 
    'ghazaryansos@shirakatsy.am', 
    'grigoryanmarina@shirakatsy.am', 
    'hakobjanyaniren@shirakatsy.am', 
    'hakobyanaksel@shirakatsy.am', 
    'hoveyanmari@shirakatsy.am', 
    'hovnanyanmaria@shirakatsy.am', 
    'jraghatspanyansrbuhi@shirakatsy.am', 
    'manukyandavit1@shirakatsy.am', 
    'manukyanlilya@shirakatsy.am', 
    'nahapetyanmaria1@shirakatsy.am', 
    'petrosyannare2@shirakatsy.am', 
    'sargsyanmari2@shirakatsy.am', 
    'shaghoyanarman@shirakatsy.am', 
    'tadevosyaneva@shirakatsy.am', 
    'yeghoyananna@shirakatsy.am'
]

tos = [class10,]

temp = []

print(sorted(list(set(temp))))